class DataBaseException(Exception): ...


class DataBaseObjectNotFoundException(DataBaseException): ...


class DataBaseObjectAlreadyExistsException(DataBaseException): ...


class DataBaseEmptyUpdateException(DataBaseException): ...


class DataBaseUnsafeDeleteException(DataBaseException): ...
